### ISSUE TITLE
Crashes when capturing front facing photo.

### ISSUE THREAD

**Issue by faizmokhtar** [zshannon/ZCSAvatarCapture#1]
I am playing around with the project demo and as soon as I tap the capture button, It crashes with this message`*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]'`.

Tracing trough the debugger, I found the culprit.

`bool isFrontFacing = self.captureDevice == [AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo][1];`

and then I change from that to this

`bool isFrontFacing = self.captureDevice == [AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo][0];`

and it seems to work fine now. 

Cool library anyway. :+1:

**Comment by ssuchanowski** [comment]
My pull request fix that.
